### ISSUE TITLE
Not compatible with PHP 8

### ISSUE THREAD

**Issue by gdandersson** [alexshelkov/SimpleAcl#15]
Deprecated: Return type of SimpleAcl\BaseObject::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/alexshelkov/simpleacl/library/SimpleAcl/BaseObject.php on line 30

**Comment by alexshelkov** [comment]
Hey, let me take a look at this on the weekends, will try to fix it this week!

**Comment by alexshelkov** [comment]
Could you tell what exactly PHP version you are using?

**Comment by gdandersson** [comment]
8.2.8

**Comment by alexshelkov** [comment]
So this should be fixed in 2.0.25. Please check
I also migrated the tests from Travis to GitHub Actions, and added tests for PHP 8.0, 8.1, 8.2.
