### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by voku** [alexshelkov/SimpleAcl#8]
maybe we can use ...

null === $this->key() here "RecursiveIterator->hasChildren()"

... and ...

null === key($this->objects) here "RecursiveIterator->key()" ?

![simpleacl](https://cloud.githubusercontent.com/assets/264695/10454049/0823231a-71b2-11e5-8f0e-8ed50fdeec0b.jpg)

**Comment by alexshelkov** [comment]
I am not sure that I understand you correctly, but is this change you wanted to make: 

```php
    public function hasChildren()
    {
        if ( is_null($this->key()) ) { // here use === null? and same for other function
            return false;
        }

        $object = $this->current();

        return count($object->getChildren()) > 0;
    }
```

**Comment by voku** [comment]
yop, but it we only get ~2% better performance with this change :/

---

I don't understand the the output from the picture (blackfire.io) 100%, because the key()-method only calls three other functions ...
1.) is_null() [~2%] 
2.) key() [~1%] 
3.) current()->getName() [6%]
 ... but what is with the rest??

``` php
    public function key()
    {
        if ( is_null(key($this->objects)) ) {
            return null;
        }

        return $this->current()->getName();
    }
```

![simpleacl](https://cloud.githubusercontent.com/assets/264695/10457902/8b3d7dd4-71c8-11e5-8abd-6bcb948c3169.jpg)

**Comment by alexshelkov** [comment]
Yes, this is_null checks should not be the good way to improve performance (even % improvement sound unrealistic). Also if performance really worry you then you shouldn't use this library in first place, as it is not supposed to be super fast.

**Comment by alexshelkov** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ZmAJSV7s&#x2F;2-test"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> test</a>
